# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905c89f41215f97964016db0c5c62a494d30d9bfc94a99a97a6c9de075e445a5c4f0c22a5a998fff1b996b147741ae67ed018efca597e989d477b1c898777051

test:
  secret_key_base: b0dfb56d7eaebc9afdcca5465002da03f2d43889c114f1a13477869df1948adc27c74a0ea8d87d56e72d39b678e3ef2281c7607f9abb118a8fb5a4dc4e43700f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
